[supervisord]
nodaemon=false
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:flos_server]
command=/Users/felipeflose/obsidian_graph_app/.venv/bin/python3 /Users/felipeflose/obsidian_graph_app/app.py
directory=/Users/felipeflose/obsidian_graph_app
autostart=true
autorestart=true
startretries=5
user=felipeflose
redirect_stderr=true
stdout_logfile=/Users/felipeflose/obsidian_graph_app/logs/server_supervisor.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
environment=PORT="8091",FLASK_DEBUG="false",PYTHONUNBUFFERED="1"

[program:flos_bot]
command=/Users/felipeflose/obsidian_graph_app/.venv/bin/python3 /Users/felipeflose/obsidian_graph_app/agent_bot.py
directory=/Users/felipeflose/obsidian_graph_app
autostart=true
autorestart=true
startretries=5
user=felipeflose
redirect_stderr=true
stdout_logfile=/Users/felipeflose/obsidian_graph_app/logs/bot_supervisor.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
environment=PYTHONUNBUFFERED="1"
